# [OPTIONAL] AWS Environment
env:
  account: "XXXXXXXXXXXX"
  region: ap-northeast-1

# Stack name
stackName: slack-chatbot

# [OPTIONAL] Log level
logLevel: INFO

# [OPTIONAL] Custom domain
domainName: slack-chatbot.example.com
certificateArn: arn:aws:acm:ap-northeast-1:XXXXXXXXXXXX:certificate/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

# Slack signing secret
slackSigningSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
# Slack bot token
slackBotToken: xoxb-xxxxxxxxxxxx-xxxxxxxxxxxxx-xxxxxxxxxxxxxxxxxxxxxxxx
# Slack bot member ID
slackBotMemberId: XXXXXXXXXXX

# ChatGPT
chatGpt:
  # OpenAI API Key
  apiKey: sk-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  # ChatGPT model
  model: gpt-4-turbo-preview

# Amazon Bedrock
bedrock:
  # Model ID
  model: "anthropic.claude-v2:1"
  # [OPTIONAL] Knowledge base ID
  kb: XXXXXXXXXX
